server.port=9093
management.server.port=9093

#######################################
#   MICROSERVICES URL CFG
#######################################
ms.url.udp-srv-query.host=http://localhost:9091

########OPENTELEMETRY################################
otel.traces.exporter=none
otel.logs.exporter=none
otel.metrics.exporter=none

otel.propagators=tracecontext,baggage

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console